### ISSUE TITLE
Atlas non-minimap GUI can't be closed normally

### ISSUE THREAD

**Issue by zabi94** [AntiqueAtlasTeam/AntiqueAtlas#92] opened 2016-11-09 16:35 UTC
#### Environment Info
>Minecraft 1.10.2, AntiqueAtlas 1.9.4-4.3.0, Forge 12.18.2.2122, Java 8, Windows 10

---

#### Mod List
>http://pastebin.com/pFMAsWsV

---

#### Description
>Right clicking an atlas brings up the GUI, but the esc button won't just close it, it will open the pause menu too. Pressing "e" has the same effect, closes the atlas but opens your inventory.

**Comment by Zsashas** [comment] 2016-11-26 16:19
I'm guessing this is at least partly to allow you to move normally while the atlas is open.

**Comment by zabi94** [comment] 2016-11-26 16:22
I'm not talking about the small minimap on the upper right corner, I'm talking about the central, fullscreen one with marker buttons, opened by right clicking the item. There is no way of closing it, and it won't allow movement 

Il 26 nov 2016 5:19 PM Zsashas <notifications@github.com> ha scritto:

I'm guessing this is at least partly to allow you to move normally while the atlas is open.

**Comment by Zsashas** [comment] 2016-11-26 16:25
I know that. While having the main map open, you can still walk and jump around. Usually GUIs prevent this, so this is likely a side effect.

**Comment by zabi94** [comment] 2016-11-26 16:28
That shouldn't be a thing, since you can't rotate your player when in this mode and the map obscures your vision... 

Il 26 nov 2016 17:25 Zsashas <notifications@github.com> ha scritto:

I know that. While having the main map open, you can still walk and jump around. Usually GUIs prevent this, so this is likely a side effect.

**Comment by Zsashas** [comment] 2016-11-26 17:08
You can't rotate the view, no, but you can still move. I've found it pretty useful.

**Comment by Kenkron** [comment] 2017-01-02 20:22
I noticed this happening a while back, but I'm glad you put it here. I might have forgotten otherwise.

**Comment by Hunternif** [comment] 2017-01-02 21:39
You should be able to move while the central Atlas GUI is open, that is by design, kind of like with the vanilla map. If in 1.9 it doesn't work then that is a bug, and so is the "Esc" button issue. Both must be fixed.

**Comment by Kenkron** [comment] 2017-05-20 00:38
On the Railcraft server, closing a map boots the player. I suspect this is why.

Edit: this seems to be a problem with marker packets.

**Comment by Kenkron** [comment] 2017-06-07 14:37
Fixed as of 1f79381611ac8c3c62f55749899aad0055791f98. Inability to move now has an issue of its own.

**Comment by Kenkron** [comment] 2017-06-07 17:11
Fix stops working if you open a sub gui.

**Closed** 2017-06-07 17:12 UTC
Labels: 1.9, type: bug

**Comment by Kenkron** [comment] 2017-06-07 17:16
Okay, now it's fixed
